//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public Applications()
        {
            this.ReportOfJob = new HashSet<ReportOfJob>();
            this.Service = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public int Address { get; set; }
        public string Owner { get; set; }
        public string Telephone { get; set; }
        public string Descrition { get; set; }
        public Nullable<int> Employer { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual List_of_housing_stock List_of_housing_stock { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ReportOfJob> ReportOfJob { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
