//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_of_housing_stock
    {
        public List_of_housing_stock()
        {
            this.Applications = new HashSet<Applications>();
            this.List_of_debts = new HashSet<List_of_debts>();
            this.Payment_Report = new HashSet<Payment_Report>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public System.DateTime Start_the_managment { get; set; }
        public int Floor { get; set; }
        public Nullable<int> Flat { get; set; }
        public int Year { get; set; }
        public decimal Area { get; set; }
    
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual ICollection<List_of_debts> List_of_debts { get; set; }
        public virtual ICollection<Payment_Report> Payment_Report { get; set; }
    }
}
