//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.List_of_debts = new HashSet<List_of_debts>();
            this.Payment_Report = new HashSet<Payment_Report>();
        }
    
        public string Owner1 { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<List_of_debts> List_of_debts { get; set; }
        public virtual ICollection<Payment_Report> Payment_Report { get; set; }
    }
}
