//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Report
    {
        public int ID { get; set; }
        public int Owner { get; set; }
        public int Address { get; set; }
        public int Flat { get; set; }
        public string Period { get; set; }
        public double Accrued { get; set; }
        public Nullable<double> Paid_for { get; set; }
    
        public virtual List_of_housing_stock List_of_housing_stock { get; set; }
        public virtual Owner Owner1 { get; set; }
    }
}
