//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOfJob
    {
        public ReportOfJob()
        {
            this.HistoryJob = new HashSet<HistoryJob>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Application { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual ICollection<HistoryJob> HistoryJob { get; set; }
        public virtual StatusReportJob StatusReportJob { get; set; }
    }
}
