//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public System.DateTime Period { get; set; }
        public int Application { get; set; }
        public int Employeer { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Users Users { get; set; }
    }
}
