//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int Id { get; set; }
        public string Status1 { get; set; }
    
        public virtual ICollection<Applications> Applications { get; set; }
    }
}
